#### Binary sensors EV Charging ########
- platform: template
  sensors:
    # True if power is over 2000W {{ 1500 < states('sensor.shelly_em_channel_1_power') | float(0) < 2500 }}
    ev_charging_onoff_2kw:
      friendly_name: 'EV is Charging with 2 kW'
      value_template: "{{ 1500 < states('sensor.shelly_em_channel_1_power') | float(0) < 2500 }}"
      device_class: battery_charging

    # True if power is over 3000W
    ev_charging_onoff_3_5kw:
      friendly_name: 'EV is Charging with 3.5 kW'
      value_template: "{{states.sensor.shelly_em_channel_1_power.state|float(0) > 3000}}"
      device_class: battery_charging

    ev_charging_onoff:
      friendly_name: 'EV is Charging'
      value_template: "{{states.sensor.ev_charging_onoff_3_5kw.state is true and states.sensor.ev_charging_onoff_2kw.state is true}}"
      device_class: battery_charging

