# Templates EV Charger 
# Templates Victron / Shelly Power meteres
- platform: template
  sensors:
    ev_charging_scheduled_onoff:
      friendly_name: 'EV charging scheduled on/off'
      value_template: "{{ 1 }}"
      
    imported_power_yearly_kwh:      
      friendly_name: "Imported Power Yearly kWh"
      device_class: energy
      unit_of_measurement: 'kWh'
      value_template: "{{(states('sensor.multiplus_grid_power') | int(default=0)) / 1000}}"  
    solar_power_yearly_kwh:
      friendly_name: "Solar Power Yearly kWh"
      device_class: energy
      unit_of_measurement: 'kWh'
      value_template: "{{(states('sensor.multiplus_solar_power') | int(default=0)) / 1000}}"
      
    shelly_em_victron_ac_loads:
      friendly_name: 'AC loads, Oven / Microwave / Dryer etc.'
      value_template: >-
          {% if ((states('sensor.multiplus_ac_loads')| int(default=0) - states('sensor.shelly_em_channel_1_power')| int(default=0) - states('sensor.shelly_em_channel_2_power')| int(default=0))  <= 0) %}
            0
          {% else %}
            {{(states('sensor.multiplus_ac_loads')| int(default=0) - states('sensor.shelly_em_channel_1_power')| int(default=0) - states('sensor.shelly_em_channel_2_power')| int(default=0))| int(default=0)}}
          {% endif %}
      unit_of_measurement: "W"
      device_class: power
    ev_battery_plug_energy_yesterday_and_night:
      friendly_name: 'EV Battery plug Energy Charged yesterday'
      value_template: "{{(states('variable.ev_battery_plug_energy_state_today') | int(default=0)  - states('variable.ev_battery_plug_energy_state_yesterday') | int(default=0)) }}"
      unit_of_measurement: "kWh"
      
    ev_battery_plug_energy_today:
      friendly_name: 'EV Battery plug Energy Charged today'
      value_template: >-
          {% if ((states('sensor.shelly_em_channel_1_energy') | int(default=0)  - states('variable.ev_battery_plug_energy_state_today') | int(default=0)) <= 0) %}
            0
          {% else %}
            {{(states('sensor.shelly_em_channel_1_energy') | int(default=0)  - states('variable.ev_battery_plug_energy_state_today') | int(default=0))}}
          {% endif %}
      unit_of_measurement: "kWh"
      
      
    ev_battery_plug_energy_today_percent:
      friendly_name: 'EV Battery plug % Charged today'
      value_template: >-
          {% if ((states('sensor.ev_battery_plug_energy_today') | float(default=0)) / (states('input_number.ev_battery_size') | float(default=0) / 100)   <= 0) %}
            0
          {% else %}
            {{(states('sensor.ev_battery_plug_energy_today') | float(default=0)) / (states('input_number.ev_battery_size') | float(default=0) / 100) | round(1)}}
          {% endif %}
      unit_of_measurement: "%"
      
    ev_battery_new_soc_estim_percent:
      friendly_name: 'EV Battery new State of Charge'
      value_template: "{{(states('sensor.ev_battery_plug_energy_today_percent') | int(default=0)) + (states('input_number.ev_battery_estimated_soc') | int(default=0) )}}"
      unit_of_measurement: "%"